backend:
  name: github
  repo: GuOshiro/portfolio
  branch: master
  site_domain: guoshiro.io

publish_mode: editorial_workflow
media_folder: "static/assets/img"
public_folder: "assets/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "api/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "string" }
      - {
          label: "Data",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Route", name: "routes", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Categoria", name: "category", widget: "string" }
      - { label: "Texto", name: "body", widget: "markdown" }
  - name: "portfolio"
    label: "Portfolio"
    folder: "api/portfolio"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Empresa", name: "company", widget: "string" }
      - { label: "URL", required: false, name: "urlProject", widget: "string" }
      - {
          label: "Descrição",
          required: false,
          name: "description",
          widget: "string",
        }
      - { label: "Imagem", required: false, name: "image", widget: "image" }
      - { label: "Route", name: "routes", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - {
          label: "Cor Primaria",
          required: false,
          name: "primaryColor",
          widget: "string",
        }
      - {
          label: "Cor Secundaria",
          required: false,
          name: "secondaryColor",
          widget: "string",
        }
